name: Scheduled API Tests

on:
  schedule:
    - cron: '0 0 * * *'  # Runs at 00:00 UTC daily

jobs:
  scheduled-test:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v3
    
    - name: Set up JDK 17
      uses: actions/setup-java@v3
      with:
        java-version: '17'
        distribution: 'temurin'
        cache: 'maven'
    
    - name: Run Performance Tests
      run: mvn test -Dtest=PerformanceTest
      
    - name: Run Security Tests
      run: mvn test -Dtest=SecurityTest
      
    - name: Generate Allure Report
      if: always()
      run: mvn allure:report
      
    - name: Upload Test Results
      if: always()
      uses: actions/upload-artifact@v3
      with:
        name: scheduled-test-results
        path: |
          target/surefire-reports
          target/site/allure-maven-plugin